# Generated by Django 4.1.3 on 2022-11-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Indoor plants', 'Indoor Plants'), ('Cacti', 'Cacti'), ('Palms', 'Palms'), ('Fruit trees', 'Fruit Trees'), ('Decorative trees', 'Decorative Trees'), ('Outside plants', 'Outside Plants'), ('Others', 'Others'), ('Herbs', 'Herbs'), ('Exotic plants', 'Exotic Plants')], max_length=30)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('joinedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
                ('text', models.CharField(max_length=1000)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_id', to='zelenyBazar.user')),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratee_id', to='zelenyBazar.user')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('locationName', models.CharField(default='Unknown', max_length=50)),
                ('locationZip', models.CharField(default='00000', max_length=5)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Meduim'), ('Hard', 'Hard'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('tradeType', models.CharField(choices=[('Free', 'Free'), ('Trade', 'Trade'), ('Sell', 'Cash')], default='Sell', max_length=10)),
                ('size', models.CharField(choices=[('1-20cm', 'First'), ('20-50cm', 'Second'), ('50-100cm', 'Third'), ('100-150cm', 'Fourth'), ('>150cm', 'Fifth'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('plantType', models.CharField(choices=[('Cut', 'Cut'), ('Seeds', 'Seeds'), ('Alive plant', 'Alive Plant'), ('Unknown', 'Unknown'), ('Other', 'Other')], default='Unknown', max_length=20)),
                ('createdOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('editedOn', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='zelenyBazar.user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='zelenyBazar.category')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=100)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zelenyBazar.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='zelenyBazar.user')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zelenyBazar.listing')),
                ('parentComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zelenyBazar.comment')),
            ],
        ),
    ]
