# Generated by Django 4.1.3 on 2022-11-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Listing',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='post',
            new_name='listing',
        ),
    ]
