# Generated by Django 4.1.3 on 2022-11-24 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0002_rename_post_listing_rename_post_image_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='tradeTypeChoices',
            new_name='TradeTypeChoices',
        ),
        migrations.AddField(
            model_name='comment',
            name='listin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='zelenyBazar.listing'),
        ),
    ]
