# Generated by Django 4.1.3 on 2022-12-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0003_alter_comment_options_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
