# Generated by Django 4.1.3 on 2022-11-24 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0004_rename_listin_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
