# Generated by Django 4.1.3 on 2022-12-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0004_listing_isfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
