# Generated by Django 4.1.3 on 2022-12-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0007_user_profilepicture_alter_comment_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_listing', to='zelenyBazar.listing'),
        ),
    ]
