# Generated by Django 4.1.3 on 2022-12-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0008_alter_image_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_listing', to='zelenyBazar.listing'),
        ),
    ]
