# Generated by Django 4.1.3 on 2022-12-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0009_alter_image_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='averageRating',
            field=models.IntegerField(default=0),
        ),
    ]
