# Generated by Django 4.1.3 on 2022-12-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0010_user_averagerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='instructions',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='listing',
            name='isListed',
            field=models.BooleanField(default=True),
        ),
    ]
