# Generated by Django 4.1.3 on 2022-12-10 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0011_listing_instructions_listing_islisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='mainImage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listing_mainpic', to='zelenyBazar.image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='averageRating',
            field=models.FloatField(default=0),
        ),
    ]
