# Generated by Django 4.1.3 on 2022-12-10 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0012_listing_mainimage_alter_user_averagerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='mainImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listing_mainpic', to='zelenyBazar.image'),
        ),
    ]
