# Generated by Django 4.1.3 on 2022-12-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0013_alter_listing_mainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='speciesCZ',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='speciesLat',
            field=models.CharField(default='', max_length=100),
        ),
    ]
