# Generated by Django 4.1.3 on 2022-12-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0014_listing_speciescz_listing_specieslat'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='environment',
            field=models.CharField(choices=[('Inside', 'Inside'), ('Outside', 'Outside'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='size',
            field=models.CharField(choices=[('1-20cm', 'One Twenty'), ('20-50cm', 'Twenty Fifty'), ('50-100cm', 'Fifty Hundred'), ('100-150cm', 'Hundred Hundredfifty'), ('>150cm', 'Hundredfifty Plus'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
    ]
