# Generated by Django 4.1.3 on 2022-12-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0015_listing_environment_alter_listing_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Cacti', 'Cacti'), ('Palms', 'Palms'), ('Fruit trees', 'Fruit Trees'), ('Decorative trees', 'Decorative Trees'), ('Others', 'Others'), ('Herbs', 'Herbs'), ('Exotic plants', 'Exotic Plants')], max_length=30),
        ),
    ]
