# Generated by Django 4.1.3 on 2022-12-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0016_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Cacti', 'Cacti'), ('Palms', 'Palms'), ('Fruit trees', 'Fruit Trees'), ('Decorative trees', 'Decorative Trees'), ('Decorative plants', 'Decorative Plants'), ('Others', 'Others'), ('Herbs', 'Herbs'), ('Exotic plants', 'Exotic Plants')], max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='environment',
            field=models.CharField(choices=[('Inside', 'Inside'), ('Outside', 'Outside'), ('Anywhere', 'Anywhere'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
    ]
