# Generated by Django 4.1.3 on 2022-12-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0017_listing_views_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Kaktusy', 'Cacti'), ('Palmy', 'Palms'), ('Ovocné stromy', 'Fruit Trees'), ('Okrasné stromy', 'Decorative Trees'), ('Okrasné keře', 'Decorative Bushes'), ('Okrasné rostliny', 'Decorative Plants'), ('Ostatní', 'Others'), ('Bylinky', 'Herbs'), ('Exotické rastliny', 'Exotic Plants'), ('Úžitkové rosltiny', 'Utility Plants'), ('Skalničky', 'Rocky Plants')], max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='difficulty',
            field=models.CharField(choices=[('Lehká', 'Easy'), ('Střední', 'Medium'), ('Ťežká', 'Hard'), ('Nezadáno', 'Unknown')], default='Nezadáno', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='environment',
            field=models.CharField(choices=[('Uvnitř', 'Inside'), ('Venku', 'Outside'), ('Všude', 'Anywhere'), ('Nezadáno', 'Unknown')], default='Nezadáno', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='plantType',
            field=models.CharField(choices=[('Řízek', 'Cut'), ('Semínka', 'Seeds'), ('Živá rostlina', 'Alive Plant'), ('Ostatní', 'Unknown'), ('Nezadáno', 'Other')], default='Ostatní', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='size',
            field=models.CharField(choices=[('1-20cm', 'One Twenty'), ('20-50cm', 'Twenty Fifty'), ('50-100cm', 'Fifty Hundred'), ('100-150cm', 'Hundred Hundredfifty'), ('>150cm', 'Hundredfifty Plus'), ('Nezadáno', 'Unknown')], default='Nezadáno', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='tradeType',
            field=models.CharField(choices=[('Zdarma', 'Free'), ('Výměna', 'Trade'), ('Prodej', 'Cash')], default='Prodej', max_length=10),
        ),
    ]
