# Generated by Django 4.1.3 on 2022-12-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelenyBazar', '0019_alter_category_name_alter_listing_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='difficulty',
            field=models.CharField(choices=[('Lehká', 'Easy'), ('Střední', 'Medium'), ('Těžká', 'Hard'), ('Nezadáno', 'Unknown')], default='Nezadáno', max_length=10),
        ),
    ]
